backend:
  name: test-repo
  # repo: casperleerink/liuxinyue
media_folder: static/assets
public_folder: /assets
logo_url: "https://cdn.dribbble.com/users/610636/screenshots/6454161/sloth_2-01.png"
collections:
  - label: "Pages" 
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "body", name: "body", widget: "markdown"}
      - label: "About Page"
        name: "about"
        file: "src/pages/about.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "body", name: "body", widget: "markdown"}
  - label: "Performance"
    name: "performance"
    folder: "src/pages/performance"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "performance-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", default: "", dateFormat: "DD.MM.YYYY", timeFormat: true}
      - {label: "Main Image", name: "mainImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}