backend:
  name: github
  repo: casperleerink/liuxinyue
media_folder: static/assets
public_folder: assets
collections:
  - name: home
    label: Homepage
    folder: home
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }