backend:
  name: github
  repo: casperleerink/liuxinyue
# media_library:
#   name: cloudinary
#   config:
#     cloud_name: casperleerink
#     api_key: 173738255589443
media_folder: static/assets
public_folder: /assets
collections:
  - name: home
    label: Homepage
    folder: content/home
    create: true
    fields:
    - name: 'image'
      label: 'Homepage Image' 
      widget: 'image'
      tagname: ''
  - name: still
    label: Still
    folder: content/home
    create: true
    fields: 
      - label: Title 
        name: title 
        widget: string
      - label: Main Image
        name: main_image
        widget: image
      - label: Gallery Images
        name: gallery_images
        widget: list
        field:
          - label: Gallery Image
            name: gallery_image
            widget: image